import Head from 'next/head'
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import { API, Amplify, Auth } from 'aws-amplify';


Amplify.configure({
  aws_project_region: 'ap-southeast-1',
  aws_cognito_region: 'ap-southeast-1',
  aws_user_pools_id: 'ap-southeast-1_gOhKSF6hy', 
  aws_user_pools_web_client_id: '63dnh9kbfdg8uautosspa1t7s',  
  aws_mandatory_sign_in: 'enable',
  aws_cloud_logic_custom: [
    {
      name: 'api-', 
      endpoint: 'https://22yndwb9fh.execute-api.ap-southeast-1.amazonaws.com/myOto', 
      region: 'ap-southeast-1' 
    }
  ]
});

export default function Home() {
  const getInfoUser = async()=>{

    const user = await Auth.currentAuthenticatedUser()
    const idToken = await user.signInUserSession.idToken.jwtToken;
  
    const headers = {
      headers:{Authorization : idToken}
    }
    const data = await API.get("api-" , "/home" , headers)
    console.log(data)
  }

 



  const sendValueToSever = async ()=>{
    const user = await Auth.currentAuthenticatedUser()
    const idToken = await user.signInUserSession.idToken.jwtToken;
    const headersPostValue = {
      headers:{Authorization : idToken},
      body:{
        name:"chien nguyen",
        address:"Viet nam",
        age:29
      }
    }
   const data =  await API.post("api-" , "/home" , headersPostValue);
   console.log(data);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Authenticator loginMechanisms={["email"]} signUpAttributes={["name","picture","email","locale","phone_number","address"]} socialProviders={["apple" ,'google' , "facebook" ]} >
      {({ signOut, user }) => (
        <main>
          <h1>Hello {user.attributes.email} - {user.attributes.name} </h1>
          <button onClick={getInfoUser}>Call api</button>
          <p>secret message</p>
          <button onClick={signOut}>Sign out</button>

          <button onClick={sendValueToSever}>Send Value</button>
        </main>
      )}
    </Authenticator>
    </>
  )
}
